import { PatternTemplate, PatternConfig } from './pattern-builder-types'

const createBaseConfig = (
  name: string,
  description: string,
  category: PatternConfig['category']
): Omit<PatternConfig, 'elements'> => ({
  id: `template-${name.toLowerCase().replace(/\s+/g, '-')}`,
  name,
  description,
  width: 400,
  height: 400,
  backgroundColor: 'oklch(0.15 0.01 260)',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  repeat: 'repeat',
  category,
})

export const patternTemplates: PatternTemplate[] = [
  {
    id: 'geometric-grid',
    name: 'Geometric Grid',
    description: 'Modern grid pattern with accent lines',
    category: 'background',
    preview: '⊞',
    config: {
      ...createBaseConfig('Geometric Grid', 'Modern grid pattern', 'background'),
      elements: [
        {
          id: 'grid-1',
          type: 'grid',
          name: 'Grid Base',
          x: 0,
          y: 0,
          width: 400,
          height: 400,
          rotation: 0,
          opacity: 0.1,
          color: 'oklch(0.75 0.15 195)',
          blendMode: 'normal',
          zIndex: 1,
          scale: 1,
          properties: {
            spacing: 40,
            lineWidth: 1,
          },
        },
      ],
    },
  },
  {
    id: 'dot-matrix',
    name: 'Dot Matrix',
    description: 'Retro dot pattern with gradient overlay',
    category: 'background',
    preview: '⣿',
    config: {
      ...createBaseConfig('Dot Matrix', 'Retro dot pattern', 'background'),
      elements: [
        {
          id: 'dots-1',
          type: 'dots',
          name: 'Dot Pattern',
          x: 0,
          y: 0,
          width: 400,
          height: 400,
          rotation: 0,
          opacity: 0.2,
          color: 'oklch(0.75 0.15 195)',
          blendMode: 'normal',
          zIndex: 1,
          scale: 1,
          properties: {
            spacing: 20,
            dotSize: 3,
          },
        },
      ],
    },
  },
  {
    id: 'wave-flow',
    name: 'Wave Flow',
    description: 'Smooth wave patterns for dynamic backgrounds',
    category: 'background',
    preview: '〰',
    config: {
      ...createBaseConfig('Wave Flow', 'Smooth wave patterns', 'background'),
      elements: [
        {
          id: 'wave-1',
          type: 'waves',
          name: 'Primary Wave',
          x: 0,
          y: 100,
          width: 400,
          height: 100,
          rotation: 0,
          opacity: 0.3,
          color: 'oklch(0.45 0.19 250)',
          blendMode: 'normal',
          zIndex: 1,
          scale: 1,
          properties: {
            amplitude: 30,
            frequency: 2,
            phase: 0,
          },
        },
        {
          id: 'wave-2',
          type: 'waves',
          name: 'Secondary Wave',
          x: 0,
          y: 200,
          width: 400,
          height: 100,
          rotation: 0,
          opacity: 0.2,
          color: 'oklch(0.75 0.15 195)',
          blendMode: 'overlay',
          zIndex: 2,
          scale: 1,
          properties: {
            amplitude: 25,
            frequency: 3,
            phase: 45,
          },
        },
      ],
    },
  },
  {
    id: 'gradient-mesh',
    name: 'Gradient Mesh',
    description: 'Layered gradients with mesh effect',
    category: 'background',
    preview: '◐',
    config: {
      ...createBaseConfig('Gradient Mesh', 'Layered gradients', 'background'),
      elements: [
        {
          id: 'gradient-1',
          type: 'gradient',
          name: 'Base Gradient',
          x: 0,
          y: 0,
          width: 400,
          height: 400,
          rotation: 45,
          opacity: 0.6,
          color: 'oklch(0.45 0.19 250)',
          blendMode: 'normal',
          zIndex: 1,
          scale: 1,
          properties: {
            gradientType: 'radial',
            colorStops: [
              { offset: 0, color: 'oklch(0.45 0.19 250)' },
              { offset: 100, color: 'transparent' },
            ],
          },
        },
        {
          id: 'gradient-2',
          type: 'gradient',
          name: 'Accent Gradient',
          x: 200,
          y: 200,
          width: 300,
          height: 300,
          rotation: -45,
          opacity: 0.4,
          color: 'oklch(0.75 0.15 195)',
          blendMode: 'screen',
          zIndex: 2,
          scale: 1,
          properties: {
            gradientType: 'radial',
            colorStops: [
              { offset: 0, color: 'oklch(0.75 0.15 195)' },
              { offset: 100, color: 'transparent' },
            ],
          },
        },
      ],
    },
  },
  {
    id: 'diagonal-stripes',
    name: 'Diagonal Stripes',
    description: 'Classic striped pattern with modern colors',
    category: 'texture',
    preview: '⟋',
    config: {
      ...createBaseConfig('Diagonal Stripes', 'Classic striped pattern', 'texture'),
      elements: [
        {
          id: 'stripes-1',
          type: 'stripes',
          name: 'Stripe Pattern',
          x: 0,
          y: 0,
          width: 400,
          height: 400,
          rotation: 45,
          opacity: 0.15,
          color: 'oklch(0.75 0.15 195)',
          blendMode: 'normal',
          zIndex: 1,
          scale: 1,
          properties: {
            spacing: 30,
            thickness: 10,
          },
        },
      ],
    },
  },
  {
    id: 'hexagon-grid',
    name: 'Hexagon Grid',
    description: 'Honeycomb hexagon pattern',
    category: 'background',
    preview: '⬡',
    config: {
      ...createBaseConfig('Hexagon Grid', 'Honeycomb pattern', 'background'),
      elements: [
        {
          id: 'hex-1',
          type: 'hexagon',
          name: 'Hexagon Pattern',
          x: 0,
          y: 0,
          width: 400,
          height: 400,
          rotation: 0,
          opacity: 0.2,
          color: 'oklch(0.45 0.19 250)',
          blendMode: 'normal',
          zIndex: 1,
          scale: 1,
          properties: {
            size: 30,
            spacing: 5,
            strokeWidth: 2,
          },
        },
      ],
    },
  },
  {
    id: 'starfield',
    name: 'Starfield',
    description: 'Scattered stars pattern',
    category: 'decoration',
    preview: '✦',
    config: {
      ...createBaseConfig('Starfield', 'Scattered stars', 'decoration'),
      elements: [
        {
          id: 'star-1',
          type: 'star',
          name: 'Star Pattern',
          x: 0,
          y: 0,
          width: 400,
          height: 400,
          rotation: 0,
          opacity: 0.3,
          color: 'oklch(0.75 0.15 195)',
          blendMode: 'normal',
          zIndex: 1,
          scale: 1,
          properties: {
            count: 30,
            minSize: 2,
            maxSize: 8,
            points: 5,
          },
        },
      ],
    },
  },
  {
    id: 'noise-texture',
    name: 'Noise Texture',
    description: 'Subtle grain texture for depth',
    category: 'texture',
    preview: '▒',
    config: {
      ...createBaseConfig('Noise Texture', 'Subtle grain texture', 'texture'),
      elements: [
        {
          id: 'noise-1',
          type: 'noise',
          name: 'Noise Layer',
          x: 0,
          y: 0,
          width: 400,
          height: 400,
          rotation: 0,
          opacity: 0.1,
          color: 'oklch(0.75 0.15 195)',
          blendMode: 'overlay',
          zIndex: 1,
          scale: 1,
          properties: {
            scale: 0.5,
            octaves: 4,
          },
        },
      ],
    },
  },
  {
    id: 'chevron-pattern',
    name: 'Chevron Pattern',
    description: 'Zigzag chevron design',
    category: 'accent',
    preview: '⋀',
    config: {
      ...createBaseConfig('Chevron Pattern', 'Zigzag chevron', 'accent'),
      elements: [
        {
          id: 'chevron-1',
          type: 'chevron',
          name: 'Chevron Lines',
          x: 0,
          y: 0,
          width: 400,
          height: 400,
          rotation: 0,
          opacity: 0.25,
          color: 'oklch(0.50 0.15 290)',
          blendMode: 'normal',
          zIndex: 1,
          scale: 1,
          properties: {
            spacing: 40,
            thickness: 8,
            angle: 45,
          },
        },
      ],
    },
  },
  {
    id: 'spiral-vortex',
    name: 'Spiral Vortex',
    description: 'Hypnotic spiral pattern',
    category: 'decoration',
    preview: '◎',
    config: {
      ...createBaseConfig('Spiral Vortex', 'Hypnotic spiral', 'decoration'),
      elements: [
        {
          id: 'spiral-1',
          type: 'spiral',
          name: 'Spiral',
          x: 200,
          y: 200,
          width: 300,
          height: 300,
          rotation: 0,
          opacity: 0.3,
          color: 'oklch(0.45 0.19 250)',
          blendMode: 'normal',
          zIndex: 1,
          scale: 1,
          properties: {
            turns: 5,
            spacing: 10,
            lineWidth: 2,
          },
        },
      ],
    },
  },
]
