import { DashboardTemplate } from './types'

export const dashboardTemplates: DashboardTemplate[] = [
  {
    id: 'analytics',
    name: 'Analytics Dashboard',
    description: 'Track metrics, KPIs, and data trends with charts and graphs',
    category: 'Business',
    tags: ['analytics', 'metrics', 'charts'],
    config: {
      name: 'Analytics Dashboard',
      description: 'Track metrics, KPIs, and data trends with charts and graphs',
      type: 'analytics',
      components: [],
      layout: {
        type: 'grid',
        columns: 12,
        gap: 24,
        padding: 24,
      },
    },
  },
  {
    id: 'crm',
    name: 'CRM Dashboard',
    description: 'Manage customers, leads, and sales pipeline',
    category: 'Sales',
    tags: ['crm', 'sales', 'customers'],
    config: {
      name: 'CRM Dashboard',
      description: 'Manage customers, leads, and sales pipeline',
      type: 'crm',
      components: [],
      layout: {
        type: 'grid',
        columns: 12,
        gap: 24,
        padding: 24,
      },
    },
  },
  {
    id: 'project',
    name: 'Project Management',
    description: 'Track tasks, milestones, and team progress',
    category: 'Productivity',
    tags: ['projects', 'tasks', 'productivity'],
    config: {
      name: 'Project Management',
      description: 'Track tasks, milestones, and team progress',
      type: 'project',
      components: [],
      layout: {
        type: 'grid',
        columns: 12,
        gap: 24,
        padding: 24,
      },
    },
  },
  {
    id: 'monitoring',
    name: 'System Monitoring',
    description: 'Real-time metrics, alerts, and system health',
    category: 'DevOps',
    tags: ['monitoring', 'system', 'devops'],
    config: {
      name: 'System Monitoring',
      description: 'Real-time metrics, alerts, and system health',
      type: 'monitoring',
      components: [],
      layout: {
        type: 'grid',
        columns: 12,
        gap: 24,
        padding: 24,
      },
    },
  },
  {
    id: 'social',
    name: 'Social Media Dashboard',
    description: 'Engagement metrics, content calendar, and audience insights',
    category: 'Marketing',
    tags: ['social', 'marketing', 'engagement'],
    config: {
      name: 'Social Media Dashboard',
      description: 'Engagement metrics, content calendar, and audience insights',
      type: 'social',
      components: [],
      layout: {
        type: 'grid',
        columns: 12,
        gap: 24,
        padding: 24,
      },
    },
  },
  {
    id: 'ecommerce',
    name: 'E-Commerce Dashboard',
    description: 'Sales, inventory, orders, and customer analytics',
    category: 'Retail',
    tags: ['ecommerce', 'sales', 'retail'],
    config: {
      name: 'E-Commerce Dashboard',
      description: 'Sales, inventory, orders, and customer analytics',
      type: 'ecommerce',
      components: [],
      layout: {
        type: 'grid',
        columns: 12,
        gap: 24,
        padding: 24,
      },
    },
  },
  {
    id: 'finance',
    name: 'Financial Dashboard',
    description: 'Revenue, expenses, cash flow, and financial forecasting',
    category: 'Finance',
    tags: ['finance', 'revenue', 'expenses'],
    config: {
      name: 'Financial Dashboard',
      description: 'Revenue, expenses, cash flow, and financial forecasting',
      type: 'finance',
      components: [],
      layout: {
        type: 'grid',
        columns: 12,
        gap: 24,
        padding: 24,
      },
    },
  },
  {
    id: 'hr',
    name: 'HR Dashboard',
    description: 'Employee data, recruitment, performance, and attendance',
    category: 'Human Resources',
    tags: ['hr', 'employees', 'recruitment'],
    config: {
      name: 'HR Dashboard',
      description: 'Employee data, recruitment, performance, and attendance',
      type: 'hr',
      components: [],
      layout: {
        type: 'grid',
        columns: 12,
        gap: 24,
        padding: 24,
      },
    },
  },
]
